name: Release
on:
  push:
    tags: ["*"]
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: |
            8
            11
            17
            21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Gradle publish
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}
        run: ./gradlew publish
